name: audiometer_sih_2023
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.1
  permission_handler: ^11.1.0 #Added by Sahil D
  audioplayers: ^5.2.1 #Added by Sahil D
  microphone: ^0.1.0 #Added by Sahil D
  google_fonts: ^4.0.4 #Added by Sahil D


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/eduapp_student_login.jpg
    - assets/images/admin.png
